Repository Jungle-TechLab/GTL_W10_T8, pull requests merged in 2025-05, with the labels that each got.

#1 migrate: 엔진 기능 리팩터링 및 코드 안정성 강화
  .github/workflows/pr_build_test.yml
  EngineSIU/EngineSIU.sln.DotSettings
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/Array.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/CString.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/String.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/String.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/HAL/PlatformType.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/JungleMath.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Matrix.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Matrix.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Quat.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Quat.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Rotator.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector4.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/WeakObjectPtr.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/BillboardComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FObjLoader.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FObjLoader.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FbxLoader.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/CameraEffectRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/LightHeatMapRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/LightHeatMapRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/WindowsFileDialog.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Windows/WindowsFileDialog.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: size/XXL

#3 Add animation sequence demo and focus improvements
  EngineSIU/EngineSIU.sln.DotSettings
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/BoneHierarchyViewerPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/BoneHierarchyViewerPanel.h
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/EditorViewportClient.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequence.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FbxLoader.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FbxLoader.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_neo_internal.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_neo_internal.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_neo_sequencer.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_neo_sequencer.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: size/XXL

#4 Feature/TOptional
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Misc/Optional.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Templates/TemplateUtilities.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: size/L

#5 Feature/animation
  EngineSIU/EngineSIU/Engine/Source/Editor/LevelEditor/SlateAppMessageHandler.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/BoneHierarchyViewerPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/BoneHierarchyViewerPanel.h
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Misc/FrameTime.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimNotify.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimNotify.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimNotifyState.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimNotifyState.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimTypes.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_neo_sequencer.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_neo_sequencer.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/Saved/AutoSaves.scene
  EngineSIU/EngineSIU/editor.ini
  EngineSIU/EngineSIU/imgui.ini
Labels: size/XXL

#6 Improve animation system with refactoring and new features
  EngineSIU/EngineSIU.sln.DotSettings
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/BoneHierarchyViewerPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/BoneHierarchyViewerPanel.h
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/BoneContainer.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimInstance.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimNodeBase.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequence.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequence.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSingleNodeInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSingleNodeInstance.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimationAsset.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimationPoseData.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimationPoseData.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimationRuntime.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimationRuntime.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/Skeleton.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/BonePose.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/BonePose.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkinnedMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Character.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Character.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Pawn.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Pawn.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/ReferenceSkeleton.h
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_neo_sequencer.cpp
  EngineSIU/EngineSIU/Engine/Source/ThirdParty/ImGui/include/ImGui/imgui_neo_sequencer.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/EngineSIU.vcxproj.filters
Labels: size/XXL

#7 Feat/bin
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Object.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequence.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequence.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/Skeleton.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/Skeleton.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Material/Material.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Material/Material.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/Asset/SkeletalMeshAsset.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/Asset/StaticMeshAsset.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FbxLoader.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/FbxLoader.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/SkeletalMesh.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/SkeletalMesh.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/StaticMesh.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/StaticMesh.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/GameFramework/Actor.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/ReferenceSkeleton.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/Define.h
Labels: size/XL

#9 fix/static_assert_revival
  EngineSIU/EngineSIU/Engine/Source/Developer/LuaTypes/LuaUserTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Container/CString.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/NameTypes.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyTypes.h
Labels: size/M

#10 Refactor animation system and UI, add sound and blending features
  EngineSIU/EngineSIU/Contents/Asset/Human.fbx
  EngineSIU/EngineSIU/Contents/Sounds/footprint.mp3
  EngineSIU/EngineSIU/Engine/Source/Contents/AnimInstance/MyAnimInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Contents/AnimInstance/MyAnimInstance.h
  EngineSIU/EngineSIU/Engine/Source/Editor/LevelEditor/SLevelEditor.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/SkeletalMeshViewerPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/SkeletalMeshViewerPanel.h
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/EditorViewportClient.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/EditorViewportClient.h
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/ImGuiWidget.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/ImGuiWidget.h
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/UnrealEd.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Quat.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Quat.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimInstance.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequence.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequence.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSingleNodeInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSoundNotify.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSoundNotify.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimStateMachine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimStateMachine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimTypes.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimationRuntime.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimationRuntime.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
  EngineSIU/EngineSIU/EngineSIU.vcxproj.filters
  EngineSIU/EngineSIU/Saved/AutoSaves.scene
  EngineSIU/EngineSIU/SoundManager.h
  EngineSIU/EngineSIU/editor.ini
  EngineSIU/EngineSIU/imgui.ini
Labels: size/XXL

#12 Refactor and improve animation logic and sound system
  EngineSIU/EngineSIU/Engine/Source/Contents/AnimInstance/MyAnimInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/SkeletalMeshViewerPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/EditorViewportClient.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Transform.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/Player.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Actors/Player.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSingleNodeInstance.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSoundNotify.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimStateMachine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/PlayerCameraManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/EditorEngine.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/EngineLoop.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Saved/AutoSaves.scene
  EngineSIU/EngineSIU/SoundManager.h
  EngineSIU/EngineSIU/editor.ini
  EngineSIU/EngineSIU/imgui.ini
Labels: size/L

#14 Object 메모리 할당 기능 수정 및 LOGFMT 개선
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Rotator.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Object.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectFactory.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectMacros.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/UObjectArray.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/UserInterface/Console.h
  README.md
Labels: enhancement, size/L

#15 Fix/shader
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/EditorViewportClient.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/Renderer.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/SkeletalMeshRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/SkeletalMeshRenderPassBase.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/SkeletalMeshRenderPassBase.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/StaticMeshRenderPass.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/TileLightCullingPass.cpp
Labels: bug

#16 fix: UObject의 소멸자 모두 삭제
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimSequenceBase.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Animation/AnimTypes.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraModifier_CameraShake.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraModifier_CameraShake.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraShakeBase.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Camera/CameraShakeBase.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/BillboardComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/BillboardComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/InputComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/AmbientLightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/AmbientLightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/DirectionalLightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/DirectionalLightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/LightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/LightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/PointLightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/PointLightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/SpotLightComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/Light/SpotLightComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ProjectileMovementComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/ProjectileMovementComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Components/SkeletalMeshComponent.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/AssetManager.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/SkeletalMesh.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/SkeletalMesh.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Level.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Renderer/ShadowManager.cpp
Labels: bug

#17 Feature: StructProperty 리플렉션 추가 및 타입 처리 개선
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Templates/TypeUtilities.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Class.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Class.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Object.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectFactory.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectMacros.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyDisplay.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ScriptStruct.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ScriptStruct.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Struct.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Struct.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/UObjectArray.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Engine/Classes/Engine/Engine.cpp
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: enhancement, size/XXL

#18 Fix: 커스텀 구조체 Display로직 수정 및 상속관계 검증 추가
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectMacros.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyDisplay.cpp
Labels: bug

#19 UI Version 2 -> Version 3 로 업데이트
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/ControlEditorPanel.h
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/OutlinerEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/Launch/ImGuiManager.cpp
Labels: enhancement, size/L

#22 Refactor and enhance property handling with added event logic
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Object.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Object.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyDisplay.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyEvent.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: enhancement, size/L

#23 Fix: EditInline 지원 추가 및 재귀적 프로퍼티 표시 개선
  EngineSIU/EngineSIU/Engine/Source/Runtime/Core/Math/Vector.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyDisplay.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyTypes.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/UObjectArray.cpp
Labels: bug, size/XL

#24 Fix: TArray<T>같은 내부 속성에 대한 런타임 검사 추가
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Struct.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Struct.h
Labels: bug

#25 Feature: Property 및 UI 컨트롤에 Metadata 지원
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/ImGuiWidget.cpp
  EngineSIU/EngineSIU/Engine/Source/Editor/UnrealEd/ImGuiWidget.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/ObjectMacros.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/Property.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyDisplay.cpp
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyMetadata.h
  EngineSIU/EngineSIU/Engine/Source/Runtime/CoreUObject/UObject/PropertyTypes.h
  EngineSIU/EngineSIU/EngineSIU.vcxproj
Labels: enhancement, size/XL
